# fly.toml file generated for silent-sea-7459 on 2023-04-06T15:36:17+02:00

app = "silent-sea-7459"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "cdg"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
