databases:
  - name: postgresql
    databaseName: rpg_on_browser_production
    user: postgresql

services:
  - type: web
    name: RPG_ON_BROWSER
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rpg_on_browser_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
