# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql

development:
  <<: *default
  database: rpg_on_browser_development

test:
  <<: *default
  database: rpg_on_browser_test

production:
  <<: *default
  database: rpg_on_browser_production
  url: <%= ENV['DATABASE_URL'] %>
  password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>
